DOMErrorCodes = {
  X_V_HTML_NO_EXPRESSION = ErrorCodes.__EXTEND_POINT__,
  X_V_HTML_WITH_CHILDREN = NaN,
  X_V_TEXT_NO_EXPRESSION = NaN,
  X_V_TEXT_WITH_CHILDREN = NaN,
  X_V_MODEL_ON_INVALID_ELEMENT = NaN,
  X_V_MODEL_ARG_ON_ELEMENT = NaN,
  X_V_MODEL_ON_FILE_INPUT_ELEMENT = NaN,
  X_V_MODEL_UNNECESSARY_VALUE = NaN,
  X_V_SHOW_NO_EXPRESSION = NaN,
  X_TRANSITION_INVALID_CHILDREN = NaN,
  __EXTEND_POINT__ = NaN
}