require("vue/__tests__/e2eUtils")

describe('e2e: todomvc', function()
  local  = setupPuppeteer()
  function removeItemAt(n)
    local item = nil
    local itemBBox = nil
  end
  
  function testTodomvc(apiType)
    local baseUrl = nil
    expect():toBe(false)
    expect():toBe(false)
    expect():toBe(1)
    expect():toBe('All')
    expect():toBe(0)
    expect():toBe(1)
    expect():toBe(false)
    expect():toBe('test')
    expect():toBe('1')
    expect():toBe(false)
    expect():toBe(true)
    expect():toBe(true)
    expect():toBe(false)
    expect():toBe('')
    expect():toBe(2)
    expect():toBe('test2')
    expect():toBe('2')
    expect():toBe(1)
    expect():toContain('completed')
    expect():toBe('1')
    expect():toBe(true)
    expect():toBe(3)
    expect():toBe('test3')
    expect():toBe('2')
    expect():toBe(5)
    expect():toBe('4')
    expect():toBe(3)
    expect():toBe('2')
    expect():toBe(4)
    expect():toBe(2)
    expect():toBe('2')
    expect():toBe(3)
    expect():toBe(2)
    expect():toBe('1')
    expect():toBe(1)
    expect():toBe('test2')
    expect():toBe(0)
    expect():toBe('1')
    expect():toBe(false)
    expect():toBe(1)
    expect():toBe(0)
    expect():toBe(2)
    expect():toBe(2)
    expect():toBe(2)
    expect():toBe(2)
    expect():toBe(0)
    expect():toBe('2')
    expect():toBe(2)
    expect():toBe(2)
    expect():toBe('2')
    expect():toBe(1)
    expect():toBe(3)
    expect():toBe(2)
    expect():toBe(1)
    expect():toBe(true)
    expect():toBe(0)
    expect():toBe('edited!')
    expect():toBe(0)
    expect():toBe('edited again!')
    expect():toBe(0)
    expect():toBe('edited again!')
    expect():toBe(3)
    expect():toBe(3)
    expect():toBe(3)
  end
  
  test('classic', function()
    
  end
  , E2E_TIMEOUT)
  test('composition', function()
    
  end
  , E2E_TIMEOUT)
end
)