require("vue/__tests__/e2eUtils")

describe('e2e: tree', function()
  local  = setupPuppeteer()
  function testTree(apiType)
    local baseUrl = nil
    expect():toBe(12)
    expect():toBe(4)
    expect():toBe(4)
    expect():toBe(false)
    expect():toBe('[+]')
    expect():toBe(true)
    expect(#()):toBe(4)
    expect():toContain('[-]')
    expect():toContain('hello')
    expect():toContain('wat')
    expect():toContain('child folder')
    expect():toContain('[+]')
    expect(#()):toBe(5)
    expect():toContain('hello')
    expect():toContain('wat')
    expect():toContain('child folder')
    expect():toContain('[+]')
    expect():toContain('new stuff')
    expect(#()):toBe(6)
    expect():toContain('hello')
    expect():toContain('wat')
    expect():toContain('child folder')
    expect():toContain('[+]')
    expect():toContain('new stuff')
    expect():toContain('new stuff')
    expect():toBe(true)
    expect():toContain('[-]')
    expect(#()):toBe(5)
    expect():toBe(false)
    expect():toContain('[+]')
    expect():toBe(true)
    expect():toContain('[-]')
    expect():toBe(15)
    expect():toBe(5)
    expect():toContain('[-]')
    expect(#()):toBe(2)
  end
  
  test('classic', function()
    
  end
  , E2E_TIMEOUT)
  test('composition', function()
    
  end
  , E2E_TIMEOUT)
end
)